# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

target 'DouYu' do

  pod 'Alamofire', '~> 3.5'
  pod 'Kingfisher', '~> 2.2.2'
end
